#!/usr/bin/env python3
"""Assemble docs/data/lanes/*.json into docs/data/curriculum.js.

- Sorts lanes by `order`.
- Adds a globally-unique `uid` (laneId:conceptId) to every concept so
  progress tracking and cross-lane links never collide.
- Emits `window.CURRICULUM = {...}` so the site works from file:// and
  GitHub Pages alike (no fetch / CORS needed).
"""
import json
import glob
import os
import re
import sys
import datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
LANES_DIR = os.path.join(ROOT, "docs", "data", "lanes")
OUT = os.path.join(ROOT, "docs", "data", "curriculum.js")

REQUIRED_CONCEPT_KEYS = [
    "id", "title", "term", "firstPrinciples", "definition", "analogy",
    "mentalModel", "diagram", "drills", "teachBack",
]


def main():
    files = sorted(glob.glob(os.path.join(LANES_DIR, "*.json")))
    if not files:
        print("No lane files found in", LANES_DIR)
        sys.exit(1)

    lanes = []
    errors = []
    seen_uids = set()
    total_concepts = total_quiz = total_gloss = 0

    for f in files:
        name = os.path.basename(f)
        try:
            data = json.load(open(f, encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            errors.append(f"{name}: invalid JSON -> {e}")
            continue

        lane_id = data.get("id") or os.path.splitext(name)[0]
        data["id"] = lane_id
        data.setdefault("order", 999)
        data.setdefault("icon", "📘")
        data.setdefault("summary", "")
        concepts = data.get("concepts", [])

        for c in concepts:
            for k in REQUIRED_CONCEPT_KEYS:
                if k not in c:
                    errors.append(f"{name}:{c.get('id','?')} missing '{k}'")
            cid = c.get("id", "concept")
            uid = f"{lane_id}:{cid}"
            base, n = uid, 2
            while uid in seen_uids:
                uid = f"{base}#{n}"
                n += 1
            seen_uids.add(uid)
            c["uid"] = uid
            c.setdefault("tags", [])
            c.setdefault("glossary", [])
            c.setdefault("sources", [])
            c.setdefault("uncertain", False)
            # Normalize Mermaid: strip a stray leading "mermaid" fence label
            # (some generators emit it) so the parser sees a valid diagram type.
            if isinstance(c.get("diagram"), str):
                c["diagram"] = re.sub(r"^\s*mermaid\s*\n", "", c["diagram"]).strip()
            if c.get("code") and not isinstance(c["code"], dict):
                c["code"] = {"language": "text", "caption": "", "content": str(c["code"])}
            total_gloss += len(c.get("glossary", []))

        total_concepts += len(concepts)
        total_quiz += len(data.get("quiz", []))
        lanes.append(data)

    lanes.sort(key=lambda d: (d.get("order", 999), d.get("title", "")))

    payload = {
        "generatedAt": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "stats": {
            "lanes": len(lanes),
            "concepts": total_concepts,
            "quiz": total_quiz,
            "glossaryTerms": total_gloss,
        },
        "lanes": lanes,
    }

    if errors:
        print("SCHEMA WARNINGS:")
        for e in errors:
            print("  -", e)

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("/* AUTO-GENERATED by build.py — do not edit by hand. */\n")
        fh.write("window.CURRICULUM = ")
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write(";\n")

    print(f"Wrote {OUT}")
    print(f"  lanes={len(lanes)} concepts={total_concepts} quiz={total_quiz} glossaryTerms={total_gloss}")
    return 0 if not errors else 0  # warnings are non-fatal


if __name__ == "__main__":
    sys.exit(main())
